name: Docker

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy Images
        run: |
          _stacks="static base"
          _stages="latest nonroot debug debug-nonroot"
          for stack in $_stacks; do 
              for stage in $_stages; do
                  docker run --rm -i -v $HOME/.docker/config.json:/root/.docker/config.json tonistiigi/repo-copy:latest gcr.io/distroless/$stack-debian10:$stage docker.io/${{ github.repository }}:$stack-$stage
              done
          done
