name: Docker

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: static-debian10
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:latest
          dst: |
            docker.io/hydrz/distroless:latest
            docker.io/hydrz/distroless:static
            docker.io/hydrz/distroless:static-debian10

      - name: static-debian10-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:nonroot
          dst: |
            docker.io/hydrz/distroless:nonroot
            docker.io/hydrz/distroless:static-nonroot
            docker.io/hydrz/distroless:static-debian10-nonroot

      - name: static-debian10-debug
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:debug
          dst: |
            docker.io/hydrz/distroless:debug
            docker.io/hydrz/distroless:static-debug
            docker.io/hydrz/distroless:static-debian10-debug

      - name: static-debian10-debug-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:debug-nonroot
          dst: |
            docker.io/hydrz/distroless:debug-nonroot
            docker.io/hydrz/distroless:static-debug-nonroot
            docker.io/hydrz/distroless:static-debian10-debug-nonroot

      - name: base-debian10
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:latest
          dst: |
            docker.io/hydrz/distroless:base
            docker.io/hydrz/distroless:base-debian10

      - name: base-debian10-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:nonroot
          dst: |
            docker.io/hydrz/distroless:base-nonroot
            docker.io/hydrz/distroless:base-debian10-nonroot

      - name: base-debian10-debug
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:debug
          dst: |
            docker.io/hydrz/distroless:base-debug
            docker.io/hydrz/distroless:base-debian10-debug

      - name: base-debian10-debug-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:debug-nonroot
          dst: |
            docker.io/hydrz/distroless:base-debug-nonroot
            docker.io/hydrz/distroless:base-debian10-debug-nonroot