name: Docker

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: static-debian10
#         uses: akhilerm/tag-push-action@v1.0.0
#         with:
#           src: gcr.io/distroless/static-debian10:latest
#           dst: |
#             docker.io/${{ github.repository }}:latest
#             docker.io/${{ github.repository }}:static
#             docker.io/${{ github.repository }}:static-debian10

      - name: static-debian10-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:nonroot
          dst: |
            docker.io/${{ github.repository }}:nonroot
            docker.io/${{ github.repository }}:static-nonroot
            docker.io/${{ github.repository }}:static-debian10-nonroot

      - name: static-debian10-debug
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:debug
          dst: |
            docker.io/${{ github.repository }}:debug
            docker.io/${{ github.repository }}:static-debug
            docker.io/${{ github.repository }}:static-debian10-debug

      - name: static-debian10-debug-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:debug-nonroot
          dst: |
            docker.io/${{ github.repository }}:debug-nonroot
            docker.io/${{ github.repository }}:static-debug-nonroot
            docker.io/${{ github.repository }}:static-debian10-debug-nonroot

      - name: base-debian10
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:latest
          dst: |
            docker.io/${{ github.repository }}:base
            docker.io/${{ github.repository }}:base-debian10

      - name: base-debian10-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:nonroot
          dst: |
            docker.io/${{ github.repository }}:base-nonroot
            docker.io/${{ github.repository }}:base-debian10-nonroot

      - name: base-debian10-debug
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:debug
          dst: |
            docker.io/${{ github.repository }}:base-debug
            docker.io/${{ github.repository }}:base-debian10-debug

      - name: base-debian10-debug-nonroot
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/base-debian10:debug-nonroot
          dst: |
            docker.io/${{ github.repository }}:base-debug-nonroot
            docker.io/${{ github.repository }}:base-debian10-debug-nonroot
