name: Docker

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy Images
        run: |
          src_project="gcr.io/distroless"
          repo_copy="tonistiigi/repo-copy:latest"
          config="$HOME/.docker/config.json"
          _stacks="static base cc python3 java"
          _stages="latest nonroot debug debug-nonroot"
          for stack in $_stacks; do 
              for stage in $_stages; do
                  tag=$([ "$stage" == latest ] && echo "$stack" || echo "$stack-$stage")
                  docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/$stack:$stage docker.io/${{ github.repository }}:$tag
              done
          done

          # default
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/$stack:latest docker.io/${{ github.repository }}:latest

          # python2.7
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/python2.7:latest docker.io/${{ github.repository }}:python2.7
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/python2.7:debug docker.io/${{ github.repository }}:python2.7-debug

          # nodejs
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:latest docker.io/hydrz/distroless:nodejs
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:debug docker.io/hydrz/distroless:nodejs-debug
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:10 docker.io/hydrz/distroless:nodejs-10
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:10-debug docker.io/hydrz/distroless:nodejs-10-debug
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:12 docker.io/hydrz/distroless:nodejs-12
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:12-debug docker.io/hydrz/distroless:nodejs-12-debug
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:14 docker.io/hydrz/distroless:nodejs-14
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/nodejs:14-debug docker.io/hydrz/distroless:nodejs-14-debug

          # java11
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/java:11 docker.io/${{ github.repository }}:java-11
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/java:11-nonroot docker.io/${{ github.repository }}:java-11-nonroot
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/java:11-debug docker.io/${{ github.repository }}:java-11-debug
          docker run --rm -i -v $config:/root/.docker/config.json $repo_copy $src_project/java:11-debug-nonroot docker.io/${{ github.repository }}:java-11-debug-nonroot
