name: Docker

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: static-debian10
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: gcr.io/distroless/static-debian10:latest
          dst: |
            docker.io/hydrz/distroless:static:latest
            docker.io/hydrz/distroless:static-debian10:latest
